# Generated by Django 5.2.13 on 2026-05-04 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("single-elimination", "Single Elimination"),
                            ("double-elimination", "Double Elimination"),
                            ("round-robin", "Round Robin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("teams", models.JSONField()),
                ("current_round", models.IntegerField(default=1)),
                ("total_rounds", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("include_bronze_match", models.BooleanField(default=False)),
                ("include_quarter_finals", models.BooleanField(default=False)),
                ("round_robin_config", models.JSONField(blank=True, null=True)),
                ("final_rankings", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("city", models.CharField(max_length=100)),
                (
                    "conference",
                    models.CharField(
                        choices=[("Eastern", "Eastern"), ("Western", "Western")],
                        max_length=20,
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("Atlantic", "Atlantic"),
                            ("Central", "Central"),
                            ("Southeast", "Southeast"),
                            ("Northwest", "Northwest"),
                            ("Pacific", "Pacific"),
                            ("Southwest", "Southwest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logo", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Matchup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchup_id", models.CharField(max_length=50)),
                ("team1", models.CharField(blank=True, max_length=100, null=True)),
                ("team2", models.CharField(blank=True, max_length=100, null=True)),
                ("winner", models.CharField(blank=True, max_length=100, null=True)),
                ("score1", models.IntegerField(blank=True, null=True)),
                ("score2", models.IntegerField(blank=True, null=True)),
                ("round", models.IntegerField()),
                ("match_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("group", "Group Stage"),
                            ("crossover", "Crossover"),
                            ("semifinal", "Semifinal"),
                            ("final", "Final"),
                            ("bronze", "Bronze Match"),
                        ],
                        default="group",
                        max_length=20,
                    ),
                ),
                (
                    "bracket_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("winners", "Winners Bracket"),
                            ("losers", "Losers Bracket"),
                            ("grand-final", "Grand Final"),
                            ("if-game", "If Game"),
                            ("crossover", "Crossover"),
                            ("playoff", "Playoff"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("bracket_group", models.IntegerField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=200, null=True)),
                ("is_bye", models.BooleanField(default=False)),
                ("is_bronze_match", models.BooleanField(default=False)),
                (
                    "next_matchup_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "loser_next_matchup_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.bracket"
                    ),
                ),
            ],
            options={
                "ordering": ["bracket", "round", "match_number"],
                "unique_together": {("bracket", "matchup_id")},
            },
        ),
        migrations.CreateModel(
            name="GamePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_winner", models.CharField(max_length=100)),
                ("confidence", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "matchup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.matchup"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("height", models.CharField(max_length=10)),
                ("weight", models.CharField(max_length=10)),
                ("position", models.CharField(max_length=10)),
                ("jersey_number", models.CharField(max_length=10)),
                ("age", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.team",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=100)),
                ("bracket_group", models.IntegerField(blank=True, null=True)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("matches_played", models.IntegerField(default=0)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.bracket"
                    ),
                ),
            ],
            options={
                "unique_together": {("bracket", "team")},
            },
        ),
    ]
